# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: asset-tracker-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/test.db:/app/test.db:Z
    environment:
      - DATABASE_URL=sqlite:///./test.db
    network_mode: "bridge"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: asset-tracker-frontend
    ports:
      - "5173:5173"
    volumes:
      - frontend_source_code:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    user: "1001:1001"
    stdin_open: true
    tty: true
    network_mode: "bridge"
    security_opt:
      - label=disable

volumes:
  frontend_source_code: 
  frontend_node_modules:
